# Generated by Django 5.0.4 on 2024-04-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_specs_product_thumbnail_alter_product_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.CharField(max_length=250),
        ),
    ]
